### ISSUE TITLE
1st Issue

### ISSUE THREAD

**Issue by tinkerbell93** [LEE-WOO-SEONG/WeatherApp_hackathon#16]
HTML
- 색상에 aria-label 추가

CSS
- body margin-top 공간
- font-family: 'Noto Sans', sans-serif

JS
- print comment 코드 수정
- 12display일때, 10시 이전에 시간에 0붙음
- setting 키보드 제어
- 배경색 랜덤 추출
- 데이터를 가져올 수 없습니다. => 위치정보를 가져 올 수 없습니다.
- console.log 지우기

**Comment by LEE-WOO-SEONG** [comment]
all clear, except setting keyboard control.
